GithubCI: build nuget packages
* Generate & upload stable release package for tags.
* Upload pre-release versions for main branch commits,
using nugetPreRelease.fsx to get a version number that
includes the date and commit hash inside it.

These packages will only be valid for the GTK platform
so when building against nonLinux platforms the consumers
of Lima will need to switch to restore and link to MAUI
nuget packages (instead of LIMA) at compile time.

diff --git a/.github/workflows/build-gtk.yml b/.github/workflows/build-gtk.yml
--- a/.github/workflows/build-gtk.yml
+++ b/.github/workflows/build-gtk.yml
@@ -29,15 +29,31 @@ jobs:
             chmod 764 $WORKLOAD_MANIFEST_DIR/*
             dotnet workload search
             dotnet workload install gtk --skip-manifest-update
+      - name: Generate pre-release version suffix
+        run: dotnet fsi nugetPreRelease.fsx "" > PreReleaseVersionSuffix.txt
       - name: Build MAUI
         run: |
             sed -i 's/_IncludeAndroid>true/_IncludeAndroid>/g' Directory.Build.Override.props
             dotnet build Microsoft.Maui.BuildTasks.slnf
-            dotnet build Microsoft.Maui.Gtk.slnf
-      - name: Build ZXing.Net.Maui
+            dotnet build -c Release Lima.slnf
+      - name: Pack MAUI
+        run: dotnet pack Lima.slnf
+      - name: Compare nuget package versions with GitInfo.txt version (sanity check)
         run: |
-            dotnet build ./src/ZXing.Net.Maui/ZXing.Net.MAUI/ZXing.Net.MAUI.csproj --framework=net8.0-gtk
-            dotnet build ./src/ZXing.Net.Maui/ZXing.Net.MAUI.Controls/ZXing.Net.MAUI.Controls.csproj --framework=net8.0-gtk
+          version_prefix=$(cat GitInfo.txt | tr -d '\n' | cut -d'-' -f1)
+          # fail if at least one of *.nupkg files' names' version portion doesn't start with version string stored in GitInfo.txt
+          # ( and ) have to be escaped when used in find command regex
+          count=$(find . -type f -name "*.nupkg" ! -regex "\(.*\/\)*\([a-zA-Z]+\.\)+${version_prefix}.*" | wc -l)
+          if [ "$count" -gt 0 ]; then
+              echo "Packages have versions that are inconsistent with version stored in GitInfo.txt. Aborting."
+              exit 1
+          fi
+      - name: Upload binaries to nuget (if tag or main branch, and nugetKey is present)
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NUGET_KEY: ${{ secrets.NUGET_KEY }}
+        if: ${{ env.NUGET_KEY != ''  && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
+        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
 
   dotnet-format:
     needs: build_and_test
